### ISSUE TITLE
Create a project logo

### ISSUE THREAD

**Issue by Bren** [RoySegall/BismarckValidator#34]

**Comment by Bren** [comment]
Check out these.
Logo for the project.
Proposed project name -
תקן פתוח

![-01](https://user-images.githubusercontent.com/133416/37305832-7cf0cd12-263e-11e8-87a5-a03ddb750123.png)

![-02](https://user-images.githubusercontent.com/133416/37305831-7cc58aa8-263e-11e8-8dfe-f19d96da07be.png)

**Comment by RoySegall** [comment]
Awesome, Can we get it in SVG format? 10x.
